# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-13 12:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cream', '0002_auto_20190213_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='user',
        ),
    ]
