# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-21 10:11
from __future__ import unicode_literals

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('cream', '0003_remove_cake_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='photo',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]
