# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-28 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('cream', '0004_cake_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', pyuploadcare.dj.models.ImageField(blank=True)),
                ('text', models.TextField(null=True)),
            ],
        ),
    ]
