# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-28 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('cream', '0006_carousel_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='C2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', pyuploadcare.dj.models.ImageField(blank=True)),
                ('text', models.TextField(null=True)),
                ('more', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='C3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', pyuploadcare.dj.models.ImageField(blank=True)),
                ('text', models.TextField(null=True)),
                ('more', models.TextField(null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Carousel',
            new_name='C1',
        ),
    ]
