# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-28 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('cream', '0007_auto_20190228_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', pyuploadcare.dj.models.ImageField(blank=True)),
                ('about', models.TextField(null=True)),
            ],
        ),
    ]
