# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-05 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cream', '0008_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('cake', models.ManyToManyField(to='cream.Cake')),
            ],
        ),
    ]
