# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-05 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cream', '0009_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='types',
            name='cake',
        ),
        migrations.DeleteModel(
            name='Types',
        ),
        migrations.AddField(
            model_name='cake',
            name='cake',
            field=models.ManyToManyField(to='cream.Type'),
        ),
    ]
