# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-05 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cream', '0011_auto_20190305_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cake',
            old_name='typ',
            new_name='Type',
        ),
    ]
