# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-05 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cream', '0014_auto_20190305_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='Type',
        ),
        migrations.AddField(
            model_name='type',
            name='cake',
            field=models.ManyToManyField(to='cream.Cake'),
        ),
    ]
