# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-05 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cream', '0015_auto_20190305_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='cake',
        ),
        migrations.AddField(
            model_name='cake',
            name='Type',
            field=models.ManyToManyField(related_name='cake_type', to='cream.Type'),
        ),
    ]
