# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-15 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('cream', '0016_auto_20190305_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='What_we_do',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_photo', pyuploadcare.dj.models.ImageField(blank=True)),
                ('small_photos', pyuploadcare.dj.models.ImageField(blank=True)),
                ('What_we_do', models.TextField(null=True)),
            ],
        ),
    ]
