# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-15 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('cream', '0017_what_we_do'),
    ]

    operations = [
        migrations.CreateModel(
            name='Small_pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_photos', pyuploadcare.dj.models.ImageField(blank=True)),
            ],
        ),
    ]
