# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-15 12:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cream', '0018_small_pic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Small_pic',
            new_name='Vsmall_pic',
        ),
    ]
