# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-15 12:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cream', '0019_auto_20190315_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='what_we_do',
            name='small_photos',
        ),
    ]
